---
# tasks file for gandi-hosting-vm

- name: Ensure gandi-hosting-vm2 package is present
  apt:
    name: gandi-hosting-vm2
    state: present
  become: true
  tags: gandi

- name: Gandi configuration file
  template:
    src: etc/default/gandi.j2
    dest: /etc/default/gandi
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: gandi

- name: Fix systemd-udevd RestrictAddressFamilies
  copy:
    dest: /etc/systemd/system/systemd-udevd.service.d/local.conf
    content: |
      [Service]
      RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6 AF_PACKET
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd daemon-reload
    - service udev restart
  become: true
  when: ansible_facts['distribution'] == "Debian" and
        ansible_facts['distribution_major_version'] == "10"
  tags: gandi


- name: Patch udev 86-gandi.rules (1/2)
  replace:
    backup: yes
    path: /etc/udev/rules.d/86-gandi.rules
    # OPTIONS+="last_rule"
    regexp: '^(.+)OPTIONS\+=\"last_rule\"(.*)$'
    replace: '\1GOTO="last_rule"\2'
  notify:
    - service udev restart
  become: true
  tags: gandi
  
- name: Patch udev 86-gandi.rules (2/2)
  lineinfile:
    backup: yes
    path: /etc/udev/rules.d/86-gandi.rules
    insertafter: EOF
    line: 'LABEL="last_rule"'
  notify:
    - service udev restart
  become: true
  tags: gandi
